### ISSUE TITLE
vcpkg ports, add repo semver tags

### ISSUE THREAD

**Issue by ebenali** [mattreecebentley/plf_queue#1]
vcpkg insists on having actual semver repository tags in the upstream.
> https://github.com/microsoft/vcpkg/pull/37402

so "v2.0.2" in-stead of "v2.02"

**Comment by mattreecebentley** [comment]
Sure, can do that. I take it the reason is that you want to include plf_queue as a downloadable library within vcpkg?

**Comment by mattreecebentley** [comment]
Fixed in the most recent version, and if you'd like me to adjust it for any of the other projects, let me know.
